file-claim:
  library:
    isa-auth-info-qualifier: "00"
    isa-auth-info: "ISA_AUTH_INFO"
    isa-security-info-qualifier: "00"
    isa-security-info: "ISA_SECURITY_INFO"
    isa-interchange-id-qualifiers:
      - "ZZ"
      - "01"
    isa-interchange-sender-id: "SENDER_ID"
    isa-interchange-receiver-id: "RECEIVER_ID"
    gs-functional-identifier-code: "HC"
    gs-application-sender-code: "APP_SENDER_CODE"
    gs-application-receiver-code: "APP_RECEIVER_CODE"
    submitter-name: "Submitter Organization"
    submitter-contact-emails:
      - "email1@example.com"
      - "email2@example.com"
